name: Main Pipeline
on:
  push:
    branches:
      - main

jobs:
  publish_release:
    name: Publish Release ðŸš€
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node ðŸ’»
        uses: actions/setup-node@v3.2.0
        with:
          node-version: '16'

      - name: Cache Node Modules ðŸ’¿
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies ðŸš§
        run: npm ci

      - name: Semantic Release ðŸš€
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # - name: Deploy To Website ðŸ’Ž
      #   uses: JamesIves/github-pages-deploy-action@v4.3.0
      #   with:
      #     branch: gh-pages
      #     folder: build
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     clean: false
      #     force: true
      #     git-config-name: github-actions[bot]
      #     git-config-email: github-actions[bot]@users.noreply.github.com
