---
name: PR Pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  code_lint:
    name: Lint Code Base ğŸ§½
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base ğŸ§½
        uses: github/super-linter/slim@v4.9.4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (.*docs\/CHANGELOG\.md|.tsconfig\.json)
          JAVASCRIPT_DEFAULT_STYLE: prettier
          TYPESCRIPT_DEFAULT_STYLE: prettier
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_BASH: false
          YAML_ERROR_ON_WARNING: true

  commitlint:
    name: commitlint ğŸ§¼
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node ğŸ’»
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'

      - name: Cache Node Modules ğŸ’¿
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: "${{ runner.os }}-build-${{ env.cache-name }}\
            -${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies ğŸš§
        run: npm ci

      - name: commitlint ğŸ§¼
        run: |
          npx commitlint \
          --from ${{ github.event.pull_request.base.sha }} \
          --to ${{ github.event.pull_request.head.sha }} \
          --verbose

  deploy:
    name: Deploy Website ğŸ’
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'arkinmodi' }}
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v3

      - name: Setup Node ğŸ’»
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'

      - name: Cache Node Modules ğŸ’¿
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: "${{ runner.os }}-build-${{ env.cache-name }}\
            -${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies ğŸš§
        run: npm ci

      - name: Build Website ğŸ—
        run: npm run build
        env:
          ENABLE_VC_BUILD: 1

      - name: Deploy Website ğŸ’
        uses: amondnet/vercel-action@v25
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_USER_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
