---
name: PR Pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  code_lint:
    name: Lint Code Base ðŸ§½
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base ðŸ§½
        uses: github/super-linter/slim@v4.9.2
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*docs\/CHANGELOG\.md
          JAVASCRIPT_DEFAULT_STYLE: prettier
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_BASH: false
          YAML_ERROR_ON_WARNING: true

  commitlint:
    name: commitlint ðŸ§¼
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node ðŸ’»
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'

      - name: Cache Node Modules ðŸ’¿
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: "${{ runner.os }}-build-${{ env.cache-name }}\
            -${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies ðŸš§
        run: npm ci

      - name: commitlint ðŸ§¼
        run: |
          npx commitlint \
          --from ${{ github.event.pull_request.base.sha }} \
          --to ${{ github.event.pull_request.head.sha }} \
          --verbose
